# Generated by Django 3.1.3 on 2020-11-29 12:48

import app
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Galeri',
                'verbose_name_plural': 'Galeri',
            },
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('template', models.CharField(max_length=35)),
                ('publish_status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Published')], default=0)),
                ('private', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('quotes', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pernikahan',
                'verbose_name_plural': 'Pernikahan',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='story_image')),
                ('wedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.wedding')),
            ],
            options={
                'verbose_name': 'Kisah Perjalan Hubungan',
                'verbose_name_plural': 'Kisah Perjalan Hubungan',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='InvitationText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('text', models.TextField()),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_text', to='app.wedding')),
            ],
            options={
                'verbose_name': 'Kalimat Undangan',
                'verbose_name_plural': 'Kalimat Undangan',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, validators=[app.validate_phone_number])),
                ('greeting', models.TextField(blank=True)),
                ('attended', models.BooleanField(default=False)),
                ('wedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.wedding')),
            ],
            options={
                'verbose_name': 'Undangan',
                'verbose_name_plural': 'Undangan',
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='gallery_image')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gallery')),
            ],
            options={
                'verbose_name': 'Foto Galeri',
                'verbose_name_plural': 'Foto Galeri',
            },
        ),
        migrations.CreateModel(
            name='Groom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50)),
                ('photo', versatileimagefield.fields.VersatileImageField(upload_to='groom_photo')),
                ('about', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True, max_length=150, null=True)),
                ('twitter', models.URLField(blank=True, max_length=150, null=True)),
                ('instagram', models.URLField(blank=True, max_length=150, null=True)),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groom', to='app.wedding')),
            ],
            options={
                'verbose_name': 'Mempelai Laki-laki',
                'verbose_name_plural': 'Mempelai Laki-laki',
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='wedding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.wedding'),
        ),
        migrations.CreateModel(
            name='Bride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50)),
                ('photo', versatileimagefield.fields.VersatileImageField(upload_to='bride_photo')),
                ('about', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True, max_length=150, null=True)),
                ('twitter', models.URLField(blank=True, max_length=150, null=True)),
                ('instagram', models.URLField(blank=True, max_length=150, null=True)),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bride', to='app.wedding')),
            ],
            options={
                'verbose_name': 'Mempelai Perempuan',
                'verbose_name_plural': 'Mempelai Perempuan',
            },
        ),
    ]
