# Generated by Django 3.1.3 on 2020-11-29 15:16

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='gallery_image'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='story_image'),
        ),
    ]
