# Generated by Django 3.1.3 on 2020-11-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='publish_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Review'), (2, 'Published')], default=0),
        ),
    ]
