# Generated by Django 3.1.3 on 2020-11-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wedding_publish_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
