# Generated by Django 3.1.3 on 2020-11-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201130_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='quotes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
