# Generated by Django 3.1.3 on 2020-11-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201129_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
