# Generated by Django 3.1.3 on 2020-11-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='key',
            new_name='code',
        ),
    ]
