# Generated by Django 3.1.3 on 2020-11-15 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201114_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Galeri'},
        ),
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name': 'Foto Galeri'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'Undangan'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Kisah Perjalan'},
        ),
        migrations.AlterModelOptions(
            name='wedding',
            options={'verbose_name': 'Konten Pernikahan'},
        ),
    ]
