# Generated by Django 3.1.3 on 2020-11-15 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201115_0331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Galeri', 'verbose_name_plural': 'Galeri'},
        ),
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name': 'Foto Galeri', 'verbose_name_plural': 'Foto Galeri'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'Undangan', 'verbose_name_plural': 'Undangan'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Kisah Perjalan', 'verbose_name_plural': 'Kisah Perjalan'},
        ),
        migrations.AlterModelOptions(
            name='wedding',
            options={'verbose_name': 'Konten Pernikahan', 'verbose_name_plural': 'Konten Pernikahan'},
        ),
    ]
