# Generated by Django 3.1.3 on 2020-11-15 14:38

import app
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201115_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[app.validate_phone_number]),
        ),
    ]
