# Generated by Django 3.1.3 on 2020-11-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_invitation_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('text', models.TextField()),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.wedding')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
