# Generated by Django 3.1.3 on 2020-11-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_invitationtext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitationtext',
            options={'verbose_name': 'Kalimat Undangan', 'verbose_name_plural': 'Kalimat Undangan'},
        ),
    ]
