# Generated by Django 3.1.3 on 2020-11-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201115_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtext',
            name='wedding',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_text', to='app.wedding'),
        ),
    ]
