# Generated by Django 3.1.3 on 2020-11-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201115_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='bride_photo',
            field=models.ImageField(blank=True, null=True, upload_to='bride'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='groom_photo',
            field=models.ImageField(blank=True, null=True, upload_to='groom'),
        ),
    ]
