# Generated by Django 3.1.3 on 2020-11-28 03:30

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='bride_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='bride_photo'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='groom_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='groom_photo'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
